version: 2

build:
  os: "ubuntu-22.04"

sphinx:
  configuration: docs/source/conf.py

formats: all

python:
  version: "3.11"
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
