codecov:
  strict_yaml_branch: master
  token: 492519e2-1bcf-4e8a-8a3e-e28be5d9de8d
coverage:
  range: 50..100
  round: down
  precision: 0
  status:
    project:
      default:
        target: auto
        threshold: 5
        only_pulls: true
    patch:
      default:
        target: auto
        threshold: 20
        only_pulls: true
comment:
  layout: "diff, files"
  require_changes: false
