#!/usr/bin/env bash

CONTAINER_TAG='htmap-dev'

set -e

docker build -t ${CONTAINER_TAG} --file docker/Dockerfile .

docker run \
  -it --rm \
  --mount type=bind,src="$PWD",dst=/home/mapper/htmap \
  -p 8000:8000 \
  -p 8888:8888 \
  ${CONTAINER_TAG} \
  $@
